// runtime.mjs — shared runtime for the design pack verification scripts.
//
// Everything these scripts need (a pinned browser and three npm packages) is
// installed into a private cache directory owned by the pack. The cache is the
// only place on disk this module writes to: it never reads, resolves, mutates or
// even looks at the dependency tree or the manifest of the repository that is
// being verified. That isolation is the whole point — the measurement tool must
// not be able to change what it measures, and must behave identically in a repo
// that has no JavaScript toolchain at all.
//
// Cache location:
//   ${SWARMERY_DESIGN_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/swarmery-design-pack}
//
// Exit codes shared by every CLI in this directory:
//   0 success
//   1 bad arguments / bad input
//   2 runtime failure (render, unreachable URL, browser launch)
//   3 runtime not prepared (cache incomplete and it cannot be completed)

import { spawnSync } from 'node:child_process';
import dns from 'node:dns/promises';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/** Resolved from `npm view <pkg> version` at implementation time. Bump deliberately:
 *  a pixel diff is only reproducible across machines while these stay identical. */
export const PINS = Object.freeze({
  playwright: '1.62.1',
  pixelmatch: '7.2.0',
  pngjs: '7.0.0',
});

export const EXIT = Object.freeze({ OK: 0, USAGE: 1, RUNTIME: 2, NOT_PREPARED: 3 });

export const SCRIPTS_DIR = path.dirname(fileURLToPath(import.meta.url));

const REGISTRY_HOST = 'registry.npmjs.org';

// A tiny ESM anchor written into the cache. Dynamic imports resolve bare
// specifiers relative to the *importing* module, so importing through this file
// makes the pinned packages resolve inside the cache and nowhere else. It also
// works for packages that ship ESM only, which `createRequire` cannot load.
const LOADER_SOURCE = [
  '// Generated by runtime.mjs — do not edit.',
  '// Anchors bare specifiers to this cache directory.',
  'export const load = (specifier) => import(specifier);',
  '',
].join('\n');

/** Print a message on stderr and exit with one of the shared codes. */
export function die(code, message) {
  process.stderr.write(`${message}\n`);
  process.exit(code);
}

/** Absolute path of the pack's private cache directory. */
export function cacheDir() {
  const explicit = (process.env.SWARMERY_DESIGN_CACHE ?? '').trim();
  if (explicit) return path.resolve(explicit);
  const xdg = (process.env.XDG_CACHE_HOME ?? '').trim();
  const base = xdg ? path.resolve(xdg) : path.join(os.homedir(), '.cache');
  return path.join(base, 'swarmery-design-pack');
}

function installedVersion(dir, name) {
  try {
    const manifest = path.join(dir, 'node_modules', name, 'package.json');
    return JSON.parse(fs.readFileSync(manifest, 'utf8')).version ?? null;
  } catch {
    return null;
  }
}

function hasChromium(browsersPath) {
  try {
    return fs.readdirSync(browsersPath).some((entry) => entry.startsWith('chromium'));
  } catch {
    return false;
  }
}

/** Read-only, offline check of what the cache is still missing. */
export function inspectRuntime(dir = cacheDir()) {
  const browsersPath = path.join(dir, 'browsers');
  const missing = [];

  for (const [name, want] of Object.entries(PINS)) {
    const got = installedVersion(dir, name);
    if (got === null) missing.push(`${name}@${want} is not installed`);
    else if (got !== want) missing.push(`${name} ${got} is installed, ${want} is pinned`);
  }
  if (!hasChromium(browsersPath)) missing.push('the pinned browser is not installed');

  let stamp = null;
  try {
    stamp = JSON.parse(fs.readFileSync(path.join(dir, 'runtime.json'), 'utf8'));
  } catch {
    stamp = null;
  }
  if (!stamp) missing.push('runtime.json is missing');
  else if (JSON.stringify(stamp.pins ?? {}) !== JSON.stringify(PINS)) {
    missing.push('runtime.json records different pins');
  }

  return { dir, browsersPath, stamp, missing, prepared: missing.length === 0 };
}

// The cache gets its own manifest so the package manager treats the cache as the
// project root and never walks up the filesystem looking for another one.
function writeCacheManifest(dir) {
  const manifest = {
    name: 'design-pack-verification-runtime',
    version: '0.0.0',
    private: true,
    description: 'Private dependency cache for the design pack verification scripts.',
  };
  fs.writeFileSync(path.join(dir, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`);
}

async function online() {
  try {
    await dns.lookup(REGISTRY_HOST);
  } catch {
    return false;
  }
  try {
    await fetch(`https://${REGISTRY_HOST}/`, {
      method: 'HEAD',
      signal: AbortSignal.timeout(4000),
    });
    return true;
  } catch {
    return false;
  }
}

async function setupFailed(stage, result) {
  if (!(await online())) {
    die(
      EXIT.NOT_PREPARED,
      'design-pack runtime is not prepared and the network is unavailable. ' +
        `Run: node ${path.join(SCRIPTS_DIR, 'ensure-runtime.mjs')} once while online.`,
    );
  }
  const detail = [result.error?.message, result.stderr, result.stdout]
    .filter(Boolean)
    .join('\n')
    .trim();
  die(EXIT.RUNTIME, `design-pack runtime setup failed during ${stage}.\n${detail}`);
}

async function installInto(dir, browsersPath, quiet) {
  writeCacheManifest(dir);
  const stdio = quiet ? 'pipe' : 'inherit';
  const env = { ...process.env, PLAYWRIGHT_BROWSERS_PATH: browsersPath };

  const specs = Object.entries(PINS).map(([name, version]) => `${name}@${version}`);
  const npm = spawnSync(
    'npm',
    ['install', '--prefix', dir, '--no-save', '--no-audit', '--no-fund', '--loglevel=error', ...specs],
    {
      cwd: dir,
      // The browser is fetched explicitly in the next step, into the cache.
      env: { ...env, PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1' },
      stdio,
      encoding: 'utf8',
    },
  );
  if (npm.error || npm.status !== 0) await setupFailed('package installation', npm);

  const cli = path.join(dir, 'node_modules', '.bin', 'playwright');
  const browser = spawnSync(cli, ['install', 'chromium'], { cwd: dir, env, stdio, encoding: 'utf8' });
  if (browser.error || browser.status !== 0) await setupFailed('browser download', browser);
}

async function makeLoader(dir) {
  const file = path.join(dir, 'loader.mjs');
  let current = null;
  try {
    current = fs.readFileSync(file, 'utf8');
  } catch {
    current = null;
  }
  if (current !== LOADER_SOURCE) fs.writeFileSync(file, LOADER_SOURCE);
  const module = await import(pathToFileURL(file).href);
  return module.load;
}

/**
 * Idempotently prepare the cache and return a handle to it.
 * Steps 1-4 of the runtime contract; every step is safe to repeat.
 *
 * @returns {Promise<{cacheDir:string, browsersPath:string, require:Function,
 *                    load:Function, pins:object, preparedAt:string|null, installed:boolean}>}
 */
export async function ensureRuntime({ quiet = false } = {}) {
  const dir = cacheDir();
  const browsersPath = path.join(dir, 'browsers');

  fs.mkdirSync(path.join(dir, 'node_modules'), { recursive: true });
  fs.mkdirSync(browsersPath, { recursive: true });
  process.env.PLAYWRIGHT_BROWSERS_PATH = browsersPath;

  let state = inspectRuntime(dir);
  let installed = false;

  if (!state.prepared) {
    if (!quiet) {
      process.stderr.write(
        `design-pack runtime: one-time setup in ${dir} — about to download ~275 MB ` +
          '(a pinned browser plus three packages, ~570 MB unpacked); this happens once, ' +
          'later runs need no network at all.\n',
      );
    }
    await installInto(dir, browsersPath, quiet);
    fs.writeFileSync(
      path.join(dir, 'runtime.json'),
      `${JSON.stringify(
        { pins: PINS, preparedAt: new Date().toISOString(), node: process.version, browsersPath },
        null,
        2,
      )}\n`,
    );
    installed = true;
    state = inspectRuntime(dir);
    if (!state.prepared) {
      die(EXIT.RUNTIME, `design-pack runtime is still incomplete after setup: ${state.missing.join('; ')}`);
    }
  }

  return {
    cacheDir: dir,
    browsersPath,
    // Contract keeps `require` for packages that ship CommonJS; `load` also
    // handles ESM-only ones. Both resolve inside the cache.
    require: createRequire(path.join(dir, 'cache-anchor.cjs')),
    load: await makeLoader(dir),
    pins: PINS,
    preparedAt: state.stamp?.preparedAt ?? null,
    installed,
  };
}

/* ── argument parsing ─────────────────────────────────────────────────────── */

const camel = (flag) => flag.replace(/^--/, '').replace(/-([a-z])/g, (_, c) => c.toUpperCase());

/**
 * Minimal flag parser. `spec` maps `--flag` to `{ type: 'flag'|'value', default }`.
 * Unknown flags and missing values are argument errors (exit 1).
 */
export function parseArgs(argv, spec, usage) {
  const out = {};
  for (const [flag, def] of Object.entries(spec)) {
    out[camel(flag)] = 'default' in def ? def.default : def.type === 'flag' ? false : null;
  }
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--help' || arg === '-h') {
      process.stdout.write(`${usage}\n`);
      process.exit(EXIT.OK);
    }
    const def = spec[arg];
    if (!def) die(EXIT.USAGE, `unknown argument: ${arg}\n\n${usage}`);
    if (def.type === 'flag') {
      out[camel(arg)] = true;
      continue;
    }
    const value = argv[i + 1];
    if (value === undefined || value.startsWith('--')) {
      die(EXIT.USAGE, `${arg} requires a value\n\n${usage}`);
    }
    out[camel(arg)] = value;
    i += 1;
  }
  return out;
}

export function parseViewport(value, usage) {
  const match = /^(\d{2,5})x(\d{2,5})$/.exec(String(value).trim());
  if (!match) die(EXIT.USAGE, `--viewport must look like 1440x900 (got "${value}")\n\n${usage}`);
  return { width: Number(match[1]), height: Number(match[2]) };
}

export function parseNumber(value, flag, usage) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed < 0) {
    die(EXIT.USAGE, `${flag} must be a non-negative number (got "${value}")\n\n${usage}`);
  }
  return parsed;
}

/* ── design input resolution ──────────────────────────────────────────────── */

function extractArchive(archive, dest) {
  let result = spawnSync('unzip', ['-q', '-o', archive, '-d', dest], { encoding: 'utf8' });
  if (result.error || result.status !== 0) {
    result = spawnSync('tar', ['-xf', archive, '-C', dest], { encoding: 'utf8' });
  }
  if (result.error || result.status !== 0) {
    die(EXIT.USAGE, `cannot extract archive ${archive}: no working "unzip" or "tar" was found`);
  }
}

function findHtml(root) {
  const found = [];
  const queue = [{ dir: root, depth: 0 }];
  while (queue.length) {
    const { dir, depth } = queue.shift();
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (depth < 4 && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
          queue.push({ dir: full, depth: depth + 1 });
        }
      } else if (/\.html?$/i.test(entry.name)) {
        found.push({ full, depth, index: /^index\.html?$/i.test(entry.name) });
      }
    }
  }
  if (!found.length) return null;
  const indexes = found.filter((f) => f.index).sort((a, b) => a.depth - b.depth);
  if (indexes.length) return indexes[0].full;
  return found.length === 1 ? found[0].full : null;
}

/**
 * Accept a `.zip`, a directory or a single HTML file and return the HTML entry
 * point plus a cleanup callback for any temporary extraction directory.
 */
export function resolveDesignInput(input) {
  const target = path.resolve(input);
  if (!fs.existsSync(target)) die(EXIT.USAGE, `input not found: ${target}`);

  const temps = [];
  let candidate = target;
  if (fs.statSync(target).isFile() && /\.zip$/i.test(target)) {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'design-pack-'));
    temps.push(tmp);
    extractArchive(target, tmp);
    candidate = tmp;
  }

  let html = candidate;
  if (fs.statSync(candidate).isDirectory()) {
    html = findHtml(candidate);
    if (!html) {
      die(EXIT.USAGE, `no index.html and no single .html file found under: ${candidate}`);
    }
  }
  return {
    html,
    cleanup: () => {
      for (const tmp of temps) fs.rmSync(tmp, { recursive: true, force: true });
    },
  };
}

/* ── browser helpers ──────────────────────────────────────────────────────── */

// Motion, carets and smooth scrolling are the three classic sources of
// non-deterministic screenshots; kill all three before capturing anything.
export const DETERMINISM_CSS =
  '*,*::before,*::after{animation-duration:0s!important;animation-delay:0s!important;' +
  'animation-iteration-count:1!important;transition-duration:0s!important;' +
  'transition-delay:0s!important;caret-color:transparent!important;scroll-behavior:auto!important}';

export async function launchChromium(runtime) {
  process.env.PLAYWRIGHT_BROWSERS_PATH = runtime.browsersPath;
  let chromium = null;
  try {
    const module = await runtime.load('playwright');
    chromium = module.chromium ?? module.default?.chromium ?? null;
  } catch (error) {
    die(EXIT.NOT_PREPARED, `cannot load the pinned browser driver from the cache: ${error.message}`);
  }
  if (!chromium) die(EXIT.NOT_PREPARED, 'the pinned browser driver in the cache exposes no chromium entry point');
  try {
    return await chromium.launch({
      args: ['--force-color-profile=srgb', '--font-render-hinting=none', '--disable-lcd-text'],
    });
  } catch (error) {
    die(EXIT.RUNTIME, `cannot launch the pinned browser: ${error.message}`);
  }
  return null;
}

export async function loadImageTools(runtime) {
  let PNG = null;
  let pixelmatch = null;
  try {
    const png = await runtime.load('pngjs');
    PNG = png.PNG ?? png.default?.PNG ?? null;
    const matcher = await runtime.load('pixelmatch');
    pixelmatch = typeof matcher === 'function' ? matcher : (matcher.default ?? null);
  } catch (error) {
    die(EXIT.NOT_PREPARED, `cannot load the pinned image packages from the cache: ${error.message}`);
  }
  if (!PNG || typeof pixelmatch !== 'function') {
    die(EXIT.NOT_PREPARED, 'the pinned image packages in the cache are incomplete');
  }
  return { PNG, pixelmatch };
}

/** Open a deterministic page: fixed viewport, no motion, fonts settled. */
export async function openPage(browser, { viewport, url, timeout = 30000 }) {
  const context = await browser.newContext({
    viewport,
    deviceScaleFactor: 1,
    reducedMotion: 'reduce',
    colorScheme: 'light',
  });
  const page = await context.newPage();
  try {
    await page.goto(url, { waitUntil: 'networkidle', timeout });
  } catch (error) {
    await context.close().catch(() => {});
    await browser.close().catch(() => {});
    die(EXIT.RUNTIME, `cannot render ${url}: ${error.message}`);
  }
  await page.addStyleTag({ content: DETERMINISM_CSS }).catch(() => {});
  await page
    .evaluate(async () => {
      await document.fonts.ready;
      return true;
    })
    .catch(() => {});
  await page.waitForTimeout(120);
  return { context, page };
}

/* ── small shared utilities ───────────────────────────────────────────────── */

export function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

export function humanBytes(bytes) {
  const units = ['B', 'KB', 'MB', 'GB'];
  let value = bytes;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  return `${value.toFixed(value >= 10 || unit === 0 ? 0 : 1)} ${units[unit]}`;
}

export function directorySize(root) {
  let total = 0;
  const stack = [root];
  while (stack.length) {
    const dir = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.isFile()) {
        try {
          total += fs.statSync(full).size;
        } catch {
          /* races during a concurrent install are not worth failing over */
        }
      }
    }
  }
  return total;
}
