package api

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/atretyak1985/swarmery/tools/swarmery/internal/taskdir"
)

// TestMintedCardReadmeSatisfiesTheLifecycleContract is the second compat anchor for
// generated task dirs (the first is in internal/wsingest, over the parser).
//
// The lifecycle actions — pause, resume, archive — rewrite a task dir's README
// status line in place. If a GENERATED README carries no line cardStatusRe matches,
// upsertCardStatus falls back to inserting one after the H1, which is tolerable but
// hides a real question: does the file the daemon writes speak the format the daemon
// reads? This asserts it does, from the actual generated bytes.
func TestMintedCardReadmeSatisfiesTheLifecycleContract(t *testing.T) {
	dir, err := taskdir.MintMicroPlan(t.TempDir(), "p", taskdir.Card{
		ExternalID: "T-42", Title: "Fix the janitor sweep", Prompt: "do the thing",
	}, time.Date(2026, 8, 17, 9, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatalf("MintMicroPlan: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	readme := string(raw)

	if !cardStatusRe.MatchString(readme) {
		t.Fatalf("the generated README has no status line the lifecycle can rewrite:\n%s", readme)
	}
	if !cardH1Re.MatchString(readme) {
		t.Errorf("the generated README has no H1:\n%s", readme)
	}

	// A pause rewrites the value in place rather than inserting a second line.
	paused := upsertCardStatus(readme, "paused")
	if strings.Count(paused, "**Status**") != 1 {
		t.Errorf("pause duplicated the status line:\n%s", paused)
	}
	if !strings.Contains(paused, "- **Status**: paused") {
		t.Errorf("pause did not take:\n%s", paused)
	}
	// And back again, so the round trip is stable.
	if resumed := upsertCardStatus(paused, "active"); !strings.Contains(resumed, "- **Status**: active") {
		t.Errorf("resume did not take:\n%s", resumed)
	}
}
